QUIZ = {
    "Easy": [
        {"pergunta": "O que significa 'variável' em programação?", "opcoes": ["Um valor que não muda", "Um valor que pode mudar durante a execução", "O nome de uma função"], "correta": 1},
        {"pergunta": "Qual operador é usado para comparação de igualdade em Python?", "opcoes": ["=", "==", "!="], "correta": 1},
        {"pergunta": "Qual é o resultado de verdadeiro AND falso?", "opcoes": ["Verdadeiro", "Falso", "Depende"], "correta": 1},
        {"pergunta": "Qual estrutura repete um bloco de código?", "opcoes": ["if", "while", "return"], "correta": 1},
        {"pergunta": "O que um algoritmo representa?", "opcoes": ["Uma sequência de passos para resolver um problema", "Um tipo de hardware", "Um erro de código"], "correta": 0},
        {"pergunta": "Qual tipo de dado representa números inteiros?", "opcoes": ["int", "float", "str"], "correta": 0},
        {"pergunta": "Como comentamos uma linha em Python?", "opcoes": ["// comentário", "# comentário", "/* comentário */"], "correta": 1},
        {"pergunta": "O que faz a função print()?", "opcoes": ["Exibe informações na tela", "Armazena dados em memória", "Cria uma variável"], "correta": 0},
        {"pergunta": "Qual operador é usado para soma?", "opcoes": ["'+'", "'-'", "'*'"], "correta": 0},
        {"pergunta": "Qual valor é considerado falso em Python?", "opcoes": ["0", "1", "'False'"], "correta": 0},
        {"pergunta": "Como iniciamos um loop que repete enquanto uma condição for verdadeira?", "opcoes": ["for", "while", "if"], "correta": 1},
        {"pergunta": "Qual destes é um tipo de dado textual?", "opcoes": ["int", "str", "bool"], "correta": 1},
        {"pergunta": "Qual palavra-chave define uma função em Python?", "opcoes": ["def", "function", "func"], "correta": 0},
        {"pergunta": "Qual símbolo representa multiplicação?", "opcoes": ["'*'", "'x'", "'^'"], "correta": 0},
        {"pergunta": "Qual é a saída de 2 + 2?", "opcoes": ["22", "4", "Erro"], "correta": 1},
        {"pergunta": "Como chamamos uma função?", "opcoes": ["nome_funcao()", "call nome_funcao", "func nome_funcao"], "correta": 0},
        {"pergunta": "Qual destes é um operador lógico?", "opcoes": ["and", "sum", "++"], "correta": 0},
        {"pergunta": "Como declaramos uma lista vazia?", "opcoes": ["'[]'", "'{}'", "'()'"], "correta": 0},
        {"pergunta": "Qual operador representa desigualdade?", "opcoes": ["!=", "==", "="], "correta": 0},
        {"pergunta": "Qual valor é considerado verdadeiro em Python?", "opcoes": ["1", "0", "''"], "correta": 0},
    ],

    "Medium": [
        {"pergunta": "Qual o resultado de 3 > 2 and 4 < 1?", "opcoes": ["Verdadeiro", "Falso", "Erro"], "correta": 1},
        {"pergunta": "Qual a saída de len('abc')?", "opcoes": ["'3'", "3", "'abc'"], "correta": 1},
        {"pergunta": "Qual erro ocorre ao acessar posição inexistente em uma lista?", "opcoes": ["TypeError", "IndexError", "ValueError"], "correta": 1},
        {"pergunta": "O que o comando 'break' faz em um loop?", "opcoes": ["Repete o loop", "Sai do loop", "Pausa o programa"], "correta": 1},
        {"pergunta": "Qual tipo de dado input() retorna?", "opcoes": ["Número", "Texto (string)", "Booleano"], "correta": 1},
        {"pergunta": "Qual é a saída de 5 // 2?", "opcoes": ["2", "2.5", "3"], "correta": 0},
        {"pergunta": "Qual operador lógico representa OU?", "opcoes": ["and", "or", "not"], "correta": 1},
        {"pergunta": "Como adicionamos um elemento ao final de uma lista?", "opcoes": ["append()", "insert()", "add()"], "correta": 0},
        {"pergunta": "O que faz a função range(5)?", "opcoes": ["Cria uma lista de 0 a 4", "Cria uma lista de 1 a 5", "Cria uma lista de 0 a 5"], "correta": 0},
        {"pergunta": "Qual operador realiza divisão com resto?", "opcoes": ["'%'", "'/'", "'//'"], "correta": 0},
        {"pergunta": "Qual o resultado de True or False?", "opcoes": ["True", "False", "Erro"], "correta": 0},
        {"pergunta": "Qual palavra-chave encerra uma função?", "opcoes": ["end", "return", "stop"], "correta": 1},
        {"pergunta": "Como removemos um elemento de uma lista pelo índice?", "opcoes": ["del", "remove", "pop"], "correta": 0},
        {"pergunta": "Qual operador tem precedência maior?", "opcoes": ["'*'", "'+'"], "correta": 0},
        {"pergunta": "Como verificamos se um item está numa lista?", "opcoes": ["in", "has", "exists"], "correta": 0},
        {"pergunta": "Qual comando exibe o tipo de um dado?", "opcoes": ["type()", "typeof()", "class()"], "correta": 0},
        {"pergunta": "Como iniciamos um dicionário vazio?", "opcoes": ["'{}'", "'[]'", "dict()"], "correta": 0},
        {"pergunta": "Qual operador compara desigualdade?", "opcoes": ["!=", "==", "="], "correta": 0},
        {"pergunta": "Qual resultado de 2 ** 3?", "opcoes": ["6", "8", "9"], "correta": 1},
        {"pergunta": "Qual método converte string para inteiro?", "opcoes": ["int()", "str()", "float()"], "correta": 0},
    ],

    "Hard": [
        {"pergunta": "Qual a complexidade da busca binária?", "opcoes": ["O(n²)", "O(log n)", "O(n)"], "correta": 1},
        {"pergunta": "No quicksort, o que é o pivô?", "opcoes": ["Menor elemento", "Valor usado para dividir a lista", "Maior elemento"], "correta": 1},
        {"pergunta": "O operador NOT faz o quê?", "opcoes": ["Inverte verdadeiro ↔ falso", "Converte para número", "Sempre retorna verdadeiro"], "correta": 0},
        {"pergunta": "Sobre funções recursivas, qual é a definição correta?", "opcoes": ["Nunca terminam", "Chamam a si mesmas", "Eliminam loops"], "correta": 1},
        {"pergunta": "O que é um algoritmo de ordenação estável?", "opcoes": ["Mantém ordem relativa de elementos iguais", "Ordena mais rápido", "Usa menos memória"], "correta": 0},
        {"pergunta": "Qual complexidade tem o bubble sort?", "opcoes": ["O(n)", "O(n²)", "O(log n)"], "correta": 1},
        {"pergunta": "O que significa recursão em programação?", "opcoes": ["Uma função que chama a si mesma", "Loop infinito", "Função condicional"], "correta": 0},
        {"pergunta": "O que faz o operador '//' em Python?", "opcoes": ["Divisão inteira", "Divisão normal", "Módulo"], "correta": 0},
        {"pergunta": "Qual é a saída de 10 % 3?", "opcoes": ["1", "3", "Erro"], "correta": 0},
        {"pergunta": "O que significa complexidade O(log n)?", "opcoes": ["Cresce linearmente", "Cresce logaritmicamente", "Cresce exponencialmente"], "correta": 1},
        {"pergunta": "Qual a função de 'pass' em Python?", "opcoes": ["Ignora a execução", "Interrompe o loop", "Retorna um valor"], "correta": 0},
        {"pergunta": "Como se define um dicionário com chave-valor?", "opcoes": ["{'chave': valor}", "[chave, valor]", "(chave, valor)"], "correta": 0},
        {"pergunta": "Qual resultado de sorted([3,1,2])?", "opcoes": ["[1,2,3]", "[3,2,1]", "[1,3,2]"], "correta": 0},
        {"pergunta": "Qual método retorna a posição de um elemento em lista?", "opcoes": ["index()", "find()", "pos()"], "correta": 0},
        {"pergunta": "Qual é a complexidade do quicksort no pior caso?", "opcoes": ["O(n log n)", "O(n²)", "O(n)"], "correta": 1},
        {"pergunta": "Qual função converte inteiro para string?", "opcoes": ["str()", "int()", "float()"], "correta": 0},
        {"pergunta": "Qual operador lógico inverte uma condição?", "opcoes": ["not", "and", "or"], "correta": 0},
        {"pergunta": "O que é um 'lambda' em Python?", "opcoes": ["Função anônima", "Loop especial", "Erro de sintaxe"], "correta": 0},
        {"pergunta": "Qual método adiciona elemento no início de lista?", "opcoes": ["insert(0, valor)", "append(valor)", "extend(valor)"], "correta": 0},
        {"pergunta": "O que significa 'imutável' em Python?", "opcoes": ["Não pode ser alterado após criação", "Pode ser modificado", "Garante performance"], "correta": 0},
    ],
}

Difficulty = ["Easy","Medium","Hard"]